# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Gruvbox dark, hard by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

[theme]
theme = "semi-native"

[theme.overrides]
idle_bg = "#1d2021"
idle_fg = "#d5c4a1"
info_bg = "#8ec07c"
info_fg = "#1d2021"
good_bg = "#b8bb26"
good_fg = "#1d2021"
warning_bg = "#fabd2f"
warning_fg = "#1d2021"
critical_bg = "#fb4934"
critical_fg = "#1d2021"

[icons]
icons = "material-nf"

[icons.overrides]
cpu = "CPU"
memory_mem = "MEM"
cpu_boost_on = "BOOST"
cpu_boost_off = ""
disk_drive = "DISK"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:30) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "weather"
autolocate = true
autolocate_interval = "once"
service.name = "metno"

[[block]]
block = "disk_space"
format = " $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $mem_avail.eng(u:B,p:M) "
format_alt = " $icon $mem_avail.eng(u:B,p:M) / $mem_total.eng(u:B,p:M) "

[[block]]
block = "cpu"
format = " $utilization "
format_alt = " $icon $utilization $frequency {$boost |}"

[[block]]
block = "maildir"
interval = 60
inboxes = ["~/.local/share/mail/gmail/INBOX"]

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $prev $play $next |}"

[[block]]
block = "sound"
if_command = "pactl list >/dev/null || aplay -l >/dev/null "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "toggle"
format = " $icon "
if_command = "networkctl status wg0"
command_state = "cat /sys/class/net/wg0/carrier"
command_on = "sudo networkctl up wg0"
command_off = "sudo networkctl down wg0"
interval = 20
merge_with_next = true

[[block]]
block = "net"
device = "^wg0$"
format = " $icon "
format_alt = " $device {$ip |}"
missing_format = ""
merge_with_next = true

[[block]]
block = "net"
device = "^wl.*$"
format = " $icon "
format_alt = " $device {$signal_strength $frequency $ssid |}{$ip |}"
missing_format = ""
merge_with_next = true

[[block]]
block = "net"
device = "^en.*$"
format = " $icon "
format_alt = " $device {$ip |}"
missing_format = ""

[[block]]
block = "battery"
device = "BAT1"
missing_format = ""
merge_with_next = true

[[block]]
block = "battery"
device = "BAT2"
missing_format = ""

[[block]]
block = "time"
interval = 1
format.full = " $timestamp.datetime(f:'%a %m/%d %T') "
format.short = " $timestamp.datetime(f:%T) "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"
