[theme]
theme = "native"

[theme.overrides]
idle_bg = "#1d2021"
idle_fg = "#d5c4a1"
info_bg = "#8ec07c"
info_fg = "#1d2021"
good_bg = "#b8bb26"
good_fg = "#1d2021"
warning_bg = "#fabd2f"
warning_fg = "#1d2021"
critical_bg = "#fb4934"
critical_fg = "#1d2021"

[icons]
icons = "material-nf"

[icons.overrides]
rss = "󰑫 "

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(rot_interval:0.5) |"
short = " $title.str(max_w:30,rot_interval:0.5) |"

[[block]]
block = "weather"
autolocate = true
autolocate_interval = "once"
service.name = "metno"
format = " $icon $temp "
format_alt = " $icon $weather $temp "

[[block]]
block = "disk_space"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "cpu"

[[block]]
block = "amd_gpu"
if_command = "lspci -v | grep 'AMD/ATI' >/dev/null"

[[block]]
block = "custom_dbus"
path = "/rss"
[[block.click]]
button = "left"
cmd = "xdg-open https://miniflux.tobyvin.dev"
update = true

[[block]]
block = "maildir"
inboxes = ["~/.local/share/mail/*/INBOX"]
interval = 60

[[block]]
block = "music"
format = "{$combo.str(w:0) $icon $prev $play $next |}"
format_alt = " $icon {$combo.str(max_w:10,rot_interval:0.5) $prev $play $next |}"

[[block]]
block = "sound"
if_command = "pactl list >/dev/null || aplay -l >/dev/null "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
device = "^wg0$"
format = " $icon "
format_alt = " $device {$ip |}"
missing_format = ""
merge_with_next = true

[[block]]
block = "net"
device = "^wl.*$"
format = " $icon "
format_alt = " $device {$signal_strength $frequency $ssid |}{$ip |}"
missing_format = ""
merge_with_next = true

[[block]]
block = "net"
device = "^en.*$"
format = " $icon "
format_alt = " $device {$ip |}"
missing_format = ""

[[block]]
block = "battery"
device = "BAT1"
missing_format = ""
merge_with_next = true

[[block]]
block = "battery"
device = "BAT2"
missing_format = ""

[[block]]
block = "time"
interval = 1
format.full = " $timestamp.datetime(f:'%a %m/%d %T') "
format.short = " $timestamp.datetime(f:%T) "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"
