[addressbooks]
[[Personal]]
path = $XDG_DATA_HOME/contacts/personal/

[general]
default_action = list

[contact table]
preferred_phone_number_type = pref, cell, home, car
preferred_email_address_type = pref, work, internet, home
