[general]
live_config_reload = true
import = ["~/.config/alacritty/theme.toml"]

[window]
dynamic_padding = true
opacity = 0.95

[font]
size = 15
normal = { family = "monospace" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{ action = "CreateNewWindow", key = "T", mods = "Control|Shift" }]
