[colors]
transparent_background_colors = true
indexed_colors = [
    { index = 16, color = "#fe8019" },
    { index = 17, color = "#d65d0e" },
    { index = 18, color = "#3c3836" },
    { index = 19, color = "#504945" },
    { index = 20, color = "#bdae93" },
    { index = 21, color = "#ebdbb2" },
]

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"
bright_foreground = "#fbf1c7"

[colors.normal]
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#ebdbb2"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"
