[shell]
program = "tmux"
args = ["new", "-A"]

[window]
dynamic_padding = true
opacity = 0.95

[font]
size = 15
normal = { family = "Hack Nerd Font" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { action = "CreateNewWindow", key = "T", mods = "Control|Shift" },
    { action = "ReceiveChar", key = "F", mode = "~Search", mods = "Control|Shift" },
    { action = "ToggleFullscreen", key = "Return", mods = "Alt" },
]
