#!/usr/bin/sh

escape() {
	printf "%s" "$1" | sed 's#\#\\#g'
}

FOCUS=$(swaymsg -t get_tree | jq '..|objects|select(.focused==true)|.name' | grep -c senpai)

if [ "$HERE" -eq 0 ] || [ "$FOCUS" -eq 0 ]; then
	notify-send "[$BUFFER] $SENDER" "$(escape "$MESSAGE")"
fi
