#!/usr/bin/env python3

import os

import requests

ICON = "\U0000f09e"


def main():
    url = "https://miniflux.tobyvin.dev/v1/feeds/counters"
    headers = {"X-Auth-Token": os.environ.get("MINIFLUX_TOKEN")}
    resp = requests.get(url, headers=headers)
    count = sum(resp.json().get("unreads").values())

    print(f" {ICON} {count} \n")
    if count > 50:
        print(os.environ.get("black"))
        print(os.environ.get("red"))
    elif count > 0:
        print(os.environ.get("black"))
        print(os.environ.get("yellow"))


if __name__ == "__main__":
    main()
