#!/usr/bin/env python3

import os

ICON = "\U000f0ee0"  # 󰻠


def main():
    with open("/proc/loadavg", "r") as stat:
        load, _ = stat.readline().split(None, 1)
    load = round(float(load))

    print(f" {ICON} {load}% \n")
    if load > 90:
        print(f"#{os.environ.get("BASE16_COLOR_00_HEX")}")
        print(f"#{os.environ.get("BASE16_COLOR_08_HEX")}")
    elif load > 60:
        print(f"#{os.environ.get("BASE16_COLOR_00_HEX")}")
        print(f"#{os.environ.get("BASE16_COLOR_0A_HEX")}")
    elif load > 30:
        print(f"#{os.environ.get("BASE16_COLOR_00_HEX")}")
        print(f"#{os.environ.get("BASE16_COLOR_0C_HEX")}")


if __name__ == "__main__":
    main()
