#!/usr/bin/env python3

import os
import linecache

ICON = "\U000f035b"  # 󰍛


def main():
    linecache.getline("/proc/meminfo", 0)
    linecache.getline("/proc/meminfo", 2)

    with open("/proc/meminfo", "r") as f:
        meminfo = dict(
            (i.split()[0].rstrip(":"), int(i.split()[1])) for i in f.readlines()
        )

    used = 100 - round(100 * meminfo["MemAvailable"] / meminfo["MemTotal"])

    print(f" {ICON} {used}% \n")
    if used > 90:
        print(f"#{os.environ.get("BASE16_COLOR_00_HEX")}")
        print(f"#{os.environ.get("BASE16_COLOR_08_HEX")}")
    elif used > 75:
        print(f"#{os.environ.get("BASE16_COLOR_00_HEX")}")
        print(f"#{os.environ.get("BASE16_COLOR_0A_HEX")}")


if __name__ == "__main__":
    main()
