#!/usr/bin/env python3

import os

import requests

ICON = "\U000f046b"  # 󰑫


def main():
    url = "https://miniflux.tobyvin.dev/v1/feeds/counters"
    headers = {"X-Auth-Token": os.environ.get("MINIFLUX_TOKEN")}
    resp = requests.get(url, headers=headers)
    count = sum(resp.json().get("unreads").values())

    print(f" {ICON} {count} \n")
    if count > 10:
        print(f"#{os.environ.get("BASE16_COLOR_00_HEX")}")
        print(f"#{os.environ.get("BASE16_COLOR_08_HEX")}")
    elif count > 0:
        print(f"#{os.environ.get("BASE16_COLOR_00_HEX")}")
        print(f"#{os.environ.get("BASE16_COLOR_0A_HEX")}")


if __name__ == "__main__":
    main()
