[templates]
defer = '{% for file in files %} zsh-defer source "{{ file }}" {% endfor %}'
contrib_fpath = 'fpath=( "{{ dir }}/contrib/completion/zsh" $fpath )'
base16_config = 'export BASE16_CONFIG_PATH="{{ dir }}"'
base16_fzf = 'export BASE16_FZF_PATH="{{ dir }}"'

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.fzf]
github = "junegunn/fzf"
use = ["completion.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-pandoc-completion]
github = "srijanshetty/zsh-pandoc-completion"
apply = ["fpath"]

[plugins.docker]
github = "docker/cli"
apply = ["contrib_fpath"]

[plugins.base16-shell]
github = "tinted-theming/base16-shell"
apply = ["defer", "base16_config"]

[plugins.base16-fzf]
github = "tinted-theming/base16-fzf"
apply = ["base16_fzf"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"
apply = ["defer"]
