[templates]
defer = '{% for file in files %} zsh-defer source "{{ file }}" {% endfor %}'
contrib_fpath = 'fpath=( "{{ dir }}/contrib/completion/zsh" $fpath )'

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-wsl]
local = '~/.local/share/wsl/shell'
profiles = ["WSL2"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.fzf]
github = "junegunn/fzf"
use = ["completion.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-pandoc-completion]
github = "srijanshetty/zsh-pandoc-completion"
apply = ["fpath"]

[plugins.docker]
github = "docker/cli"
apply = ["contrib_fpath"]

[plugins.base16]
github = "chriskempson/base16-shell"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"
apply = ["defer"]

[plugins.compinit]
local = '~/.local/share/zsh/plugins'
apply = ["defer"]
