[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
comp = { value = 'mkdir -p "$XDG_DATA_HOME/zsh/site-functions"; ln -sf "{{ file }}" "$XDG_DATA_HOME/zsh/site-functions/_{{ name }}"', each = true }

[plugins.zsh-wsl]
inline = 'test -f ~/.local/share/zsh-wsl && zsh-defer source ~/.local/share/zsh-wsl'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-shift-select]
github = "jirutka/zsh-shift-select"
apply = ["defer"]

[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-pandoc-completion]
github = "srijanshetty/zsh-pandoc-completion"
apply = ["defer"]

[plugins.dotnet]
remote = "https://raw.githubusercontent.com/dotnet/cli/master/scripts/register-completions.zsh"
apply = ["comp"]

[plugins.docker]
remote = "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker"
apply = ["comp"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.compinit]
inline = 'mkdir -p $XDG_CACHE_HOME/zsh && autoload -Uz compinit && zsh-defer compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION'

