U = require("tobyvin.utils")
require("tobyvin.options")
require("tobyvin.filetype")
require("tobyvin.autocmds")
require("tobyvin.keymaps")
require("tobyvin.commands")
require("tobyvin.lsp")
require("tobyvin.diagnostic")
require("tobyvin.lazy")

vim.cmd.colorscheme("gruvbox")
