local latest = vim.version.range("*")

vim.pack.add({
	"https://github.com/ellisonleao/gruvbox.nvim",
	{ src = "https://github.com/emmanueltouzery/plenary.nvim", version = "winborder" },
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main", data = {
		build = "TSUpdate",
	} },
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects", version = "main" },
	{ src = "https://github.com/stevearc/oil.nvim", version = latest },
	{ src = "https://github.com/williamboman/mason.nvim", version = latest, data = {
		build = "MasonUpdate",
	} },
	{ src = "https://github.com/mfussenegger/nvim-lint", version = latest },
	{ src = "https://github.com/stevearc/conform.nvim", version = latest },
	{ src = "https://github.com/codethread/qmk.nvim", version = latest },
	{ src = "https://github.com/lewis6991/gitsigns.nvim", version = latest },
	{ src = "https://github.com/j-hui/fidget.nvim", version = latest },
	"https://github.com/nvim-telescope/telescope.nvim",
	"https://github.com/nvim-telescope/telescope-live-grep-args.nvim",
	"https://github.com/debugloop/telescope-undo.nvim",
	{ src = "https://github.com/nvim-telescope/telescope-fzf-native.nvim", data = {
		build = { "make" },
	} },
	{ src = "https://github.com/3rd/image.nvim", version = latest },
	"https://github.com/kiyoon/magick.nvim",
	{ src = "https://github.com/folke/lazydev.nvim", version = latest },
	"https://github.com/Bilal2453/luvit-meta",
	"https://github.com/LuaCATS/tex-luatex",
	"https://github.com/LuaCATS/tex-lualatex",
	"https://github.com/LuaCATS/tex-luametatex",
	"https://github.com/LuaCATS/tex-lualibs",
	"https://github.com/disco0/mpv-types-lua",
	"https://gitlab.com/carsakiller/cc-tweaked-documentation.git",
	{
		src = "https://github.com/f3fora/nvim-texlabconfig",
		data = { build = { "go", "build", "-o", vim.fs.joinpath(vim.env.HOME, ".local/bin/") } },
	},
	"https://github.com/vxpm/ferris.nvim",
	"https://github.com/mfussenegger/nvim-jdtls",
	"https://github.com/microsoft/python-type-stubs",
	"https://github.com/b0o/SchemaStore.nvim",
	"https://github.com/tridactyl/vim-tridactyl",
	"https://github.com/hjson/vim-hjson",
	"https://github.com/nfnty/vim-nftables",
	"https://github.com/wilriker/gcode.vim",
	"https://github.com/andweeb/presence.nvim",
	"https://github.com/eandrju/cellular-automaton.nvim",
	"https://github.com/rktjmp/playtime.nvim",
}, {
	load = true,
	confirm = #vim.api.nvim_list_uis() ~= 0,
})
