display-name = "Toby Vincent"
downloads-dir = "~/dl"
signature = "Toby Vincent"
email-listing-page-size = 50
email-reading-verify-cmd = "gpg --verify -q"
email-reading-decrypt-cmd = "gpg -dq"
email-writing-sign-cmd = "gpg -o - -saq"
email-writing-encrypt-cmd = "gpg -o - -eqar"
notify-cmd = "notify-send '[MAIL] <sender>' '<subject>'"

[gmail]
default = true
email = "tobyv13@gmail.com"

backend = "imap"
imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "tobyv13@gmail.com"
imap-passwd-cmd = "pass show gmail"

sender = "smtp"
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "tobyv13@gmail.com"
smtp-passwd-cmd = "pass show gmail"

watch-cmds = ["himalaya --output json search NEW | jq -r '.|length' >> /tmp/himalaya-counter"]

[gmail.folder-aliases]
inbox = "INBOX"
sent = "[Gmail]/Sent Mail"
drafts = "[Gmail]/Drafts"
trash = "[Gmail]/Trash"
