#!/bin/sh

notmuch tag +notify -- \(tag:new and tag:unread\) folder:/INBOX\$/ folder:/Junk\$/
notmuch tag +inbox -- tag:new folder:/INBOX\$/
notmuch tag +sent -- tag:new folder:/Sent\$/
notmuch tag +draft -- tag:new folder:/Draft\$/
notmuch tag +spam -- tag:new folder:/Junk\$/
notmuch tag +trash -- tag:new folder:/Trash\$/
notmuch tag -new -- tag:new
"$HOME"/.local/bin/notmuch-notify
