# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Gruvbox dark, hard by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

[theme]
theme = "semi-native"

[theme.overrides]
idle_bg = "#1d2021"
idle_fg = "#d5c4a1"
info_bg = "#8ec07c"
info_fg = "#1d2021"
good_bg = "#b8bb26"
good_fg = "#1d2021"
warning_bg = "#fabd2f"
warning_fg = "#1d2021"
critical_bg = "#fb4934"
critical_fg = "#1d2021"

[icons]
icons = "none"

[icons.overrides]
bat_charging = "BAT+"
music = "\U000f075a"       # nf-md-music
music_next = "\U000f04ad"  # nf-md-skip_next
music_pause = "\U000f03e4" # nf-md-pause
music_play = "\U000f040a"  # nf-md-play
music_prev = "\U000f04ae"  # nf-md-skip_previous
weather_clouds = "\ue33d"  # nf-weather-cloud
weather_default = "\ue33d" # Cloud symbol as default
weather_rain = "\ue371"    # nf-weather-raindrop
weather_snow = "\ue36f"    # nf-weather-snowflake_cold
weather_sun = "\ue30d"     # nf-weather-day_sunny
weather_thunder = "\ue31d" # nf-weather-thunderstorm

[[block]]
block = "weather"
autolocate = true
autolocate_interval = "once"
service.name = "metno"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2)"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "nvidia_gpu"
# show_memory = false
# show_clocks = true

[[block]]
block = "sound"
if_command = "pactl list >/dev/null || aplay -l >/dev/null "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
device = "^wl.*$"
format = " $icon {$ssid |}"
format_alt = " $icon {$signal_strength $frequency $ssid |}"
missing_format = ""

[[block]]
block = "battery"
device = "BAT1"
format = " $icon $percentage "
full_format = " FULL "
empty_format = " $icon $percentage "
missing_format = ""

[[block]]
block = "battery"
device = "BAT2"
format = " $icon $percentage "
full_format = " FULL "
empty_format = " $icon $percentage "
missing_format = ""

[[block]]
block = "time"
interval = 1
format.full = " $timestamp.datetime(f:'%a %m/%d %T') "
format.short = " $timestamp.datetime(f:%T) "

[[block]]
block = "music"
player = "spotifyd"
format = " $icon {$combo.str(max_w:20) $prev $play $next |}"
