# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Gruvbox dark, hard by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

[theme]
name = "semi-native"

[theme.overrides]
idle_bg = "#1d2021"
idle_fg = "#d5c4a1"
info_bg = "#8ec07c"
info_fg = "#1d2021"
good_bg = "#b8bb26"
good_fg = "#1d2021"
warning_bg = "#fabd2f"
warning_fg = "#1d2021"
critical_bg = "#fb4934"
critical_fg = "#1d2021"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "nvidia_gpu"
# show_memory = false
# show_clocks = true

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotifyd"
buttons = ["prev", "play", "next"]

[[block]]
block = "battery"
device = "/sys/class/power_supply/BAT0"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "battery"
device = "/sys/class/power_supply/BAT1"
if_command = "test -e /sys/class/power_supply/BAT1"

[[block]]
block = "battery"
device = "/sys/class/power_supply/BAT2"
if_command = "test -e /sys/class/power_supply/BAT2"

# install: go install github.com/monban/iwdstatus
[[block]]
block = "custom"
command = "iwdstatus"
json = true
if_command = "command -v iwdstatus"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
