require("tobyvin.options")
require("tobyvin.filetype")
require("tobyvin.autocmds")
require("tobyvin.keymaps")
require("tobyvin.lsp")
require("tobyvin.diagnostic")
require("tobyvin.lazy")
require("tobyvin.utils.dashboard")

vim.cmd.colorscheme("gruvbox")
