typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'

ZSH_THEME="powerlevel10k/powerlevel10k"
HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_TITLE="true"
ZSH_CUSTOM_AUTOUPDATE_QUIET=true
setopt HIST_IGNORE_ALL_DUPS
setopt NO_BEEP
setopt MENU_COMPLETE