#!/usr/bin/env zsh

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_TITLE="true"
setopt HIST_IGNORE_ALL_DUPS
setopt NO_BEEP
setopt MENU_COMPLETE