#!/usr/bin/env zsh

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_TITLE="true"
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern line)
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion)

setopt NO_BEEP
setopt MENU_COMPLETE
setopt appendhistory
# setopt HIST_IGNORE_ALL_DUPS

fpath=(~/.local/share/zsh/site-functions "${fpath[@]}")

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
for f in ~/.zsh/*.*sh; do source $f; done

eval "$(starship init zsh)"

function set_win_title() {
    folder=$(sed "s/$USER/~/g" <<<$PWD:t)

    window_title="\033]0;$USER@$HOST: $folder\007"
    echo -ne "$window_title"
}

precmd_functions+=(set_win_title)

autoload -U compinit
compinit -i

zstyle ':completion:*' menu select
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
