shell:
  program: C:\WINDOWS\system32\wsl.exe
  args:
    - "tmux new -As home"

working_directory: '\\wsl$\Arch\home\tobyv'

font:
  normal:
    family: FiraCode NF
    style: Regular
  bold:
    family: FiraCode NF
    style: Bold
  italic:
    family: FiraCode NF
    style: Italic
  bold_italic:
    family: FiraCode NF
    style: Bold Italic

window:
  opacity: 0.98
