shell:
  program: C:\WINDOWS\system32\wsl.exe
  args:
    - "--user"
    - "root"
    - machinectl shell --uid=1000 --quiet .host /bin/zsh -l -c 'tmux new -As $USER'

working_directory: '\\wsl$\Arch\home\tobyv'

font:
  normal:
    family: FiraCode NF

window:
  opacity: 0.98
